# Generated by Django 5.1.1 on 2024-11-12 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0004_alter_investigator_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Investigator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hero.investigator'),
        ),
    ]
