# Generated by Django 5.1.1 on 2024-11-24 01:18

import hero.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0005_article_investigator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to=hero.models.get_upload)),
            ],
        ),
    ]
