# Generated by Django 5.1.1 on 2024-11-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0009_article_photo_superhero_photo_alter_article_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
