# Generated by Django 5.1.1 on 2024-11-25 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0010_alter_photo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.RemoveField(
            model_name='superhero',
            name='image',
        ),
    ]
