name: dolphin-app
region: nyc

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

databases:
  - engine: PG
    name: db
    num_nodes: 1
    size: db-s-dev-database
    version: "12"

features:
  - buildpack-stack=ubuntu-22

ingress:
  rules:
    - component:
        name: pythonwebapps-student-07-superhe
      match:
        path:
          prefix: /
    - component:
        name: pythonwebapps-student-07-superh2
      match:
        path:
          prefix: /static

services:
  - name: pythonwebapps-student-07-superhe
    environment_slug: python
    github:
      branch: main
      deploy_on_push: true
      repo: JLeFevre559/PythonWebApps
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    source_dir: Student/08/Superhero
    run_command: |-
      python manage.py migrate --noinput
      python manage.py loaddata database.json
      python manage.py createsuperuser --noinput
      gunicorn --worker-tmp-dir /dev/shm config.wsgi
    envs:
      - key: DISABLE_COLLECTSTATIC
        scope: RUN_AND_BUILD_TIME
        value: "1"
      - key: DJANGO_SUPERUSER_EMAIL
        scope: RUN_AND_BUILD_TIME
        value: jlefevre559@gmail.com
      - key: DJANGO_SUPERUSER_USERNAME
        scope: RUN_AND_BUILD_TIME
        value: admin
      - key: DJANGO_SUPERUSER_PASSWORD
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:oAJuWqBdHnxeKxsCNHiStqmQbw1VDIz6:1htlQW9ot4J1wbrvj9hsvqHCnWRzrxaB37z+rVig]
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: POSTGRES_DB
        scope: RUN_AND_BUILD_TIME
        value: ${db.DATABASE}
      - key: POSTGRES_HOST
        scope: RUN_AND_BUILD_TIME
        value: ${db.HOSTNAME}
      - key: POSTGRES_USER
        scope: RUN_AND_BUILD_TIME
        value: ${db.USERNAME}
      - key: POSTGRES_PASSWORD
        scope: RUN_AND_BUILD_TIME
        value: ${db.PASSWORD}
      - key: POSTGRES_PORT
        scope: RUN_AND_BUILD_TIME
        value: ${db.PORT}

static_sites:
  - name: pythonwebapps-student-07-superh2
    environment_slug: html
    github:
      branch: main
      deploy_on_push: true
      repo: JLeFevre559/PythonWebApps
    source_dir: Student/08/Superhero/static
